### ISSUE TITLE
vob4 exits not correct

### ISSUE THREAD

**Issue by chrboe** [authorblues/smwrandomizer#1]
The huge array in randomizer.js contains the following line
`{"name": "vob4", "world": 7, "exits": 2, "castle": 0, [...] "out": ["sw5"]},`
which lists vob4 as having 2 exits, but only one is supplied in `out` (c7 is missing).

I'm not sure whether this is intended, but I wouldn't see why it would be.

**Comment by authorblues** [comment]
Fixed in v1.3. :+1:
