### ISSUE TITLE
Game Breaking Bug in Chocolate Island 2

### ISSUE THREAD

**Issue by GameGlitchGuy** [authorblues/smwrandomizer#10]
First of all I'd just like to say that i love the additions to the randomizer since v1.4 it's very fun to play. However during my playthrough of 4 different seeds I've encountered a game crash in chocolate island 2 every time. Videos below.

2 videos with the seed shown at the beginning

https://www.youtube.com/watch?v=troV3_H698c

https://www.youtube.com/watch?v=jhHLidPL2hA

1 video without the seed shown but included anyway 

https://www.youtube.com/watch?v=H57o2s5k3bQ

**Comment by authorblues** [comment]
Should be fixed by https://github.com/authorblues/smwrandomizer/commit/49780d096598704d1645d104e33fa59d108c2e7c
