### ISSUE TITLE
Infinite Loop in YI2

### ISSUE THREAD

**Issue by timschellenberg** [authorblues/smwrandomizer#12]
Seed FA367F55-8BD9

Cut the race we meant to have really short when the very first level goes in a pipe -> bonus game -> pipe back to the first room ad infinitum.

**Comment by Ankouno** [comment]
It's actually working as intended there. Try the previous pipe.

Though, we may make it not mess with ordering like that if too many people are getting confused by it.

**Comment by timschellenberg** [comment]
We got to the same level in the next race and figured it out.
Sorry lmao
