### ISSUE TITLE
Unused TEST level replaced a level causing it to be unbeatable.

### ISSUE THREAD

**Issue by LuigiXHero** [authorblues/smwrandomizer#15]
Seed: 7a8e3a47

It's the ghost house in World 2 the one that unlocks top secret area. Sorry that I forgot what it's called.
[rom.zip](https://github.com/authorblues/smwrandomizer/files/358462/rom.zip)

**Comment by authorblues** [comment]
Out of curiousity, did you happen to enable "95 exit mode"? (If not, do you recall what flags you had set?)

**Comment by LuigiXHero** [comment]
I don't remember what settings I choice, I just remember wanting chaos so I enabled almost everything.

So yeah I think it might have been enabled.
