### ISSUE TITLE
Generation not working due to js error

### ISSUE THREAD

**Issue by Lui37** [authorblues/smwrandomizer#17]
I keep getting "TypeError: LEVEL_MODES[meta.lmode] is undefined" every time when generating a rom with any of the presets.

**Comment by authorblues** [comment]
What browser and version are you using?

**Comment by authorblues** [comment]
Please reopen if this does not fix the problem.

**Comment by Lui37** [comment]
That's gone, though I get "TypeError: getLevelMode(...) is undefined" now. I'm on ff 47.0.1

(also apparently i can't reopen this one shrug)

**Comment by authorblues** [comment]
Sorry about that. Seems like minor browser differences. I'll test on Firefox and get it fixed within the hour.

**Comment by authorblues** [comment]
Let me know if that cleared things up.
