### ISSUE TITLE
Missing animations in levels

### ISSUE THREAD

**Issue by Lui37** [authorblues/smwrandomizer#19]
ROM: https://authorblues.github.io/smwrandomizer/#!/3a3d321c/xf09f85cf3e0 (92d9)

Levels such as 11, 13, 1B and a bunch of others are all missing animations, both palette and graphics related.

**Comment by authorblues** [comment]
I believe this is fixed by 37998cd07a53ee86898210e0cf3f4ea03ac1f810. Please re-open if not.
