### ISSUE TITLE
game crash after block snake room

### ISSUE THREAD

**Issue by churine** [authorblues/smwrandomizer#20]
fb5c6adc (I forgot the seed options, unfortunately- though music, sprites and (☆^O^☆) were on)
In the first level of the special world (map location), after entering the door at the end of the first room (Larry's castle room with the block snake) the game crashed trying to load the next room
well, the screen was fully black and the game was completely unresponsive, but music did still play

**Comment by authorblues** [comment]
Can you attach the rom as a file to this at least?

**Comment by authorblues** [comment]
I believe this was fixed by c4c4f2afd42ff9e6b6d106870dd57a32796f3ea2
