### ISSUE TITLE
Garbled sprites

### ISSUE THREAD

**Issue by Niamek** [authorblues/smwrandomizer#22]
![smw-v2 2-7bd7af60000](https://cloud.githubusercontent.com/assets/15385566/17783768/7b4e6848-6547-11e6-98e8-406c0ae2bb62.png)

I encounted that in this file: [smw-v2.2-7bd7af60.zip](https://github.com/authorblues/smwrandomizer/files/425507/smw-v2.2-7bd7af60.zip)

Go to the first star you would go if you did a speedrun of the normal game. You should end up in the star world and see two boos house. On that boo house I could enter, I entered the door on the up that would normally lead to the big boo's room. But instead lead me tehre with the garbled sprites.

PS: I have a small question too, but don't know where to ask, hopefully it's alright if I ask it here : it seems that 95 exits is not in the option now? I did not see also big changes in enemies properties so I am wondering what are these properties.

**Comment by Niamek** [comment]
Another case.

![smw-v2 2-6f290f88000](https://cloud.githubusercontent.com/assets/15385566/17789420/1f28b17c-6560-11e6-809f-c9d1d8f7d6a0.png)

[smw-v2.2-6f290f88.zip](https://github.com/authorblues/smwrandomizer/files/425821/smw-v2.2-6f290f88.zip)

Go left. Enter the star(after beating the first level). Go to the end of the level with the blue yoshi. After going in the pipe, you are now in the level of the screenshot and you should see that garbled tougue.

**Comment by Niamek** [comment]
ROM: http://authorblues.github.io/smwrandomizer/#!/d595c648/8 (206a)

Yet another case.

![smw-v2 2-d595c648000](https://cloud.githubusercontent.com/assets/15385566/17826527/8c3fed40-663f-11e6-9405-d8f110429e11.png)

Go to blue P-button level(It replaces the star under the boo house near the star of the game)

**Comment by authorblues** [comment]
Thanks for all the notes. Having a few issues with sprite tilesets.

**Comment by Niamek** [comment]
Yuo are welcome, authorblues.

If I find other stuffs like that, do you want me to continue? Or you have enough test cases.(I am having so much fun with this, so I don't mind continuing that hunting)

**Comment by authorblues** [comment]
If you find any cases that seem to be different enough, let me know. If it's just more broken sprites, go ahead and post it. The screenshots help a lot too.

**Comment by authorblues** [comment]
To answer your original question: 

**95 Exits** just affected how stages got rearranged, but no one was using it and it was causing some problems, so it was removed. **Randomize powerups** just changes where feathers/flowers/mushrooms are. **Enemy properties** refers to which koopas give you which yoshi abilities.

**Comment by Niamek** [comment]
ROM: http://authorblues.github.io/smwrandomizer/#!/a09dab0e/8 (f6cc)

![smw-v2 2-a09dab0e000](https://cloud.githubusercontent.com/assets/15385566/17941988/8b656c8e-6a03-11e6-85df-9d0e66dc04dd.png)
Another case. It's right in the beginning of the game: the right level of yoshi's house. I didn't take a screenshot, but the ghosts that make a line of ghost are pretty nasty. On the screen I joined you see the mole head, but when it should turns into an actual ghost, you see a crushes rex.

Oh okay, thank for the clarification concerning my questions.

**Comment by authorblues** [comment]
Thanks, I'm having an issue with the occasional stage having the wrong sprite tileset, so I think I'm on track with solving this bug.

**Comment by Niamek** [comment]
ROM: http://authorblues.github.io/smwrandomizer/#!/ad8d90fc/8 (f2a3)

![Uploading smw-v2.2-ad8d90fc000.png…]()

Go to Donut plains level 1(after the first castle), go in the first possible pipe.

**Comment by Niamek** [comment]
![smw-v2 2-ad8d90fc000](https://cloud.githubusercontent.com/assets/15385566/19014848/e5baf4f8-87c5-11e6-8e6b-3820cd529fe1.png)
