### ISSUE TITLE
Crash on seed 28fcf9e4

### ISSUE THREAD

**Issue by Mario1211** [authorblues/smwrandomizer#25]
ROM: http://authorblues.github.io/smwrandomizer/#!/28fcf9e4/8

In the 7th level in the special world, which is a castle named gnarly, it crashes as soon as i enter the first door.

**Comment by authorblues** [comment]
I **think** this crash was resolved by https://github.com/authorblues/smwrandomizer/commit/c4c4f2afd42ff9e6b6d106870dd57a32796f3ea2. Please feel free to reopen this issue if the crash persists.
