### ISSUE TITLE
how to apply to emulator

### ISSUE THREAD

**Issue by gremmaster565** [authorblues/smwrandomizer#26]
Ive set up all the things on the website and put the rom in but I dont know what to do next, when I click the button to generate the edited rom a line of text pops up in the box where .setgoal was. 

Btw i use snes9x and openemu

**Comment by Niamek** [comment]
For that line of text, is for SpeedRunsLive. You should ignore that.

Generating the rom should pop up a window asking you if you wat to save something (with a name like smw-v2.2-XXXXXX). You need to open that file in the emulator and it should work.

If nothing open, it's probably your browser.

**Comment by gremmaster565** [comment]
Thank you

**Comment by Niamek** [comment]
Can you confirm you succeeded to play a randomized game?

**Comment by gremmaster565** [comment]
Yes
