### ISSUE TITLE
Error when swapping Bowser frontdoor and backdoor

### ISSUE THREAD

**Issue by mirrormagic1** [authorblues/smwrandomizer#30]
When ever I try to randomize SMW It Gives me this error.
ValidationError: Randomized ROM did not pass validation.

Sublevel 0x1DB of frontdoor(@frontdoor) is empty
Sublevel 0x1F2 of frontdoor(@frontdoor) is empty
Sublevel 0x1E2 reachable from 2 stages: vob2(@bgh), frontdoor(@frontdoor)

It makes it impossible to Create a rom.
Browser: Chrome
- Settings:
  Randomly Swap Stages (Sorta the point, ya know?)
  Randomize Sublevels
  Randomize Exits (Swap Normal/Secret Randomly)
  Randomize Warps
  Random Stage
  Randomize Chaotically
  Shuffle Enemies
  Custom Yoshi Color Abilities
  Shuffle Koopa Kids
  Randomize Boss Difficulty (Koopa Kids, Big Boo, Reznor, Bowser)
  Bowser's Castle - default
  Randomize Powerups
  Randomize Level Exits (Yoshi Wings, Keys, etc.)
  Randomize Stage Color Palettes
  Randomize Autoscrollers
  Randomly Add Water to Stages
  Saving-After Every Level
  Custom Stage Names
  Custom Text (Message Boxes, Cutscenes, etc.)
  Randomize Music (Please don't!)

I know the rom is valid but it wont work no matter how hard I try

Edit: I managed to pinpoint the problem To it being "Randomize Sublevels", It seems Bugged Oddly enough.

**Comment by authorblues** [comment]
I think this might be fixed. Please re-open if not.
