### ISSUE TITLE
eating a pokey in one gulp

### ISSUE THREAD

**Issue by Niamek** [authorblues/smwrandomizer#32]
Preset: funky
V. 2.2
seed: 4284BA39-37AC

Eating a pokey with a yoshi on the level to the right is weird: he eats the pokey in one gulp, It replace the sumo enemy that creates a thunder and flame thing with his legs.

It seems that the enemy is swapped, but not perfectly as the pokey can be eaten in one gulp.

**Comment by authorblues** [comment]
If yoshi is at the same horizontal level as the pokey, he can always rapidly eat the segments. This occurs in vanilla SMW
