### ISSUE TITLE
Special World

### ISSUE THREAD

**Issue by stevebobtherando** [authorblues/smwrandomizer#34]
The special world isn't randomized (The levels are the same as normal, just with the Mario heads on everything).

**Comment by authorblues** [comment]
Can you attach a copy of the rom and the seed/settings you used?

**Comment by stevebobtherando** [comment]
How do I find it (On Mac)

**Comment by authorblues** [comment]
Somewhere in your browser downloads folder

**Comment by stevebobtherando** [comment]
The file name is smw-v2.2-8c1556ed.sfc  I can't find anything else on it,
sorry.

**Comment by EnderofGames** [comment]
I am aware that this post is almost a year old, but it is sitting open and unmoved, so: 

<img width="514" alt="special overview" src="https://user-images.githubusercontent.com/17417666/30777229-349354e6-a073-11e7-8856-41a31dd3fb68.PNG">

The levels in _star world_ and _special world_ can both seen to be changed in the seed "8c1556ed" from the 2.2 version of the SMW randomizer, although a world not being changed would be a possibility, although unlikely. The fortress, castle, and ghost house levels on the overworld are accurate to the levels they describe. 

Special world in play:
<img width="753" alt="special1" src="https://user-images.githubusercontent.com/17417666/30777257-ab2e655a-a073-11e7-828f-59ece7604104.PNG">
Special world 1:
<img width="753" alt="special2" src="https://user-images.githubusercontent.com/17417666/30777259-ab2fabb8-a073-11e7-984c-d771d00c33ae.PNG">
Special world 2:
<img width="753" alt="special3" src="https://user-images.githubusercontent.com/17417666/30777258-ab2f21b6-a073-11e7-8738-3b9a089ac824.PNG">

Unless you have a file to upload that has this glitch, the seed itself does not reflect this problem, so this issue can be closed.
