### ISSUE TITLE
How do i download the rom?

### ISSUE THREAD

**Issue by AshcantKetchum** [authorblues/smwrandomizer#36]
I wanted to use this, but when I chose my settings, it didn't let me download it. Is it because I'm on mobile? Please help me!

**Comment by authorblues** [comment]
Not sure if the tool will support mobile. You have to provide an unmodified rom as well.

**Comment by AshcantKetchum** [comment]
So. I have to have a super mario rom? I do have that do I insert it where it says chose rom? Also thanks for being so quick with it

**Comment by authorblues** [comment]
Yes, you need to provide the base, unmodified SMW rom in that box.

**Comment by AshcantKetchum** [comment]
The rom I have doesn't work. Where do you recommend getting the rom?

**Comment by authorblues** [comment]
https://github.com/authorblues/smwrandomizer/raw/gh-pages/smw.sfc

**Comment by AshcantKetchum** [comment]
Thank you
