### ISSUE TITLE
I have a few suggestions that you'll want to hear :)

### ISSUE THREAD

**Issue by Corndog52** [authorblues/smwrandomizer#39]
I'm pretty sure that all of the games included in Super Mario All-Stars (and the + Super Mario World edit) use the same level engine as Super Mario World. That being said...

Ideas:

*Depending on the game you chose, that will be the physics for your version of Mario or Luigi (or Peach or Toad if Super Mario USA/Super Mario Bros. 2 was selected).

*Any levels/courses/stages will be chosen to be part of that randomization.

*Could you make the randomizer also work for...
[Super Mario World 2: Yoshi's Island]
[Hacks of Super Mario World, including other ROMs put in the randomizer]
[Hacks of Super Mario World 2]

Thank you for reading this.

P.S. I realize that seeds would be trickier to work with due to cross-game compatibility hopefully going in the works.

**Comment by authorblues** [comment]
> I'm pretty sure that all of the games included in Super Mario All-Stars (and the + Super Mario World edit) use the same level engine as Super Mario World.

It doesn't.

> Depending on the game you chose, that will be the physics for your version of Mario or Luigi (or Peach or Toad if Super Mario USA/Super Mario Bros. 2 was selected).

I can't.

> Any levels/courses/stages will be chosen to be part of that randomization.

It won't.

> Could you make the randomizer also work for...

Not even one of those. None of those are possible.
