### ISSUE TITLE
After Selecting my Options, How do I Download the ROM? (SOLVED)

### ISSUE THREAD

**Issue by Bj007pro** [authorblues/smwrandomizer#41]
~~So after I added the ROM file (U version), and choose the options I wanted, I hit the generate button. But for some reason, it doesn't start the download or anything, and there's no other button that would represent on clicking  to download the file.~~

Nevermind, found the secret. 😉

**Comment by matty678best** [comment]
how do you do it @Bj007pro D:

**Comment by ghost** [comment]
how u do it

**Comment by TheLemon27** [comment]
How?
