### ISSUE TITLE
how do i download the rom

### ISSUE THREAD

**Issue by ghost** [authorblues/smwrandomizer#46]
when i press the button nothing happens

**Comment by Ra1N2** [comment]
idk where to get the original ntscu rom.someone help plz??

**Comment by deadhitter1** [comment]
I have the same problem. I keep generating it. Then it says some error about front doors for like 50 times, then when I generate a ROM that is probably just fine, there's no download prompted or anything. Man fuck this site, that's annoying.

**Comment by deadhitter1** [comment]
it only works when opened on iexplore.exe

**Comment by authorblues** [comment]
:rofl: Sorry that my personal project that I do for free in my free time has some bugs. I feel really bad now. That must have been really inconvenient for you.

**Comment by logan879** [comment]
I'm on Mac I do what I want put the rom it needs and then click generate rom and nothing happens
