### ISSUE TITLE
Yoshi wings exit ≠ secret path

### ISSUE THREAD

**Issue by Damonpulse** [authorblues/smwrandomizer#47]
An issue I'm ending up having is stages with a flying Yoshi bonus locking into certain red spots. The problem is: if you take the Yoshi bonus, when you finish it, the normal path will be unlocked (if it isn't already) and not the secret path. This can make certain stages unreachable, such as the water stage in donut plains, as an example. Maybe add something into the code that has the randomizer favor putting stages with yoshi bonuses in spots where not being able to unlock the secret path is negligible. (Such as a point that originally had a yoshi bonus, or one where you can get to a certain stage some other way, like in the Forest of Illusion or the "Bowser Zone")

**Comment by authorblues** [comment]
All of those stages still have valid normal and secret exits that are unrelated to the yoshi wings.
