### ISSUE TITLE
Random Luigi

### ISSUE THREAD

**Issue by lakshun** [authorblues/smwrandomizer#60]
ROM: http://authorblues.github.io/smwrandomizer/#!/80f33340/xf09f2583260 (7ec8)

The Randomizer decides on its own whether Player 1 is Mario or Luigi. Since Luigi is much harder to control than Mario due to his longer sliding I have to delete the randomized rom every time I get Luigi (which is more often than not) and try again hoping I get Mario.

There needs to be a way to disable Luigi as player 1.

**Comment by authorblues** [comment]
Luigi is just Mario with the color green. He controls the same.
