### ISSUE TITLE
"Generate Rom" button doesn't work

### ISSUE THREAD

**Issue by lakshun** [authorblues/smwrandomizer#61]
After setting the randomizer up the way I want I clicked the "Report an Issue" button and then went back to the randomizer page (I'm on Chrome). 
I selected the rom on my pc to randomize again but the "Generate Rom" button was grayed out and unclickable.

Probably easily fixed by simply always opening the "Report an Issue" page in a new tab.

**Comment by authorblues** [comment]
Will fix in next version, new UI.
