### ISSUE TITLE
Same few level location randomizations

### ISSUE THREAD

**Issue by gloe0027** [authorblues/smwrandomizer#62]
Your randomizer is fantastic! Thanks for creating it for public use!!! I just had one small issue.

It seems that there are a small number of pre-created level randomizations that are reused for the location randomization feature. After awhile, the randomizations become recognizable and predictable since there are so few of them. Will new ones be added soon? Or, will a true randomization be generated at each seed created in future releases to fix this problem?

Also, will there be any updates to this randomizer in the future? It seems that the last update was over a year ago, and I was wondering if any changes and/or added features were planned for the future. Again, thanks for creating an awesome randomizer!

**Comment by authorblues** [comment]
The issue you're encountering is based on certain requirements for where levels can go, for a variety of reasons. Next version should hopefully remove some, but not all, of these restrictions.
