### ISSUE TITLE
Unexpected Checksum Error

### ISSUE THREAD

**Issue by Openemu25700** [authorblues/smwrandomizer#63]
Hello,

Today, i wanted to randomize a ROM, but when i click on "Generate ROM", **nothing happens**.
So, i went in the source code of the site, and there was an error

"Error: **Base rom incorrect**. Expected checksum 0xB19ED489, got 0x3C41070F"

What should i do?

**Comment by Ankouno** [comment]
This error means that you have an unclean (modified) SMW ROM. The randomizer requires the ROM be unedited to ensure we can make changes where we need to.
Most likely, this just means either:
A) You accidentally edited it with Lunar Magic (or some other tool) at some point.
B) The place you downloaded from did not provide a proper ROM.
C) You're using the wrong version (we require the U version, not J or E).
Whatever the case, you'll just have to download a new ROM and try that instead.
