### ISSUE TITLE
Difficulty changer

### ISSUE THREAD

**Issue by colt05** [authorblues/smwrandomizer#7]
Suggestion: Add a "Difficulty Changer" which has 4 settings: Easy, Normal, Hard, and Super Hard. :D 
EDIT: The presets have a difficulty also, but those cannot be customized.

**Comment by Damonpulse** [comment]
A very good idea. My first two randomizations had the harder levels showing up on Yoshi's Island, of all places!

**Comment by authorblues** [comment]
Will try to have better difficulty presets in v3.0 UI
