### ISSUE TITLE
Chocolate Island 2 Bug

### ISSUE THREAD

**Issue by ZimPractical** [authorblues/smwrandomizer#8]
So while I was playing the newest version of SMW Randomizer, I encountered a weird, game freezing bug while playing the level Chocolate Island 2 (with Randomizer it can be hard to figure out what I mean by "Chocolate Island 2". I mean the the actual level, not the overworld location, name, or anything else like that) When going into the fourth section of the level (I believe the normal exit), the game started to freak out and freeze. I also have a screenshot of the glitch. Please fix this, as I wasn't able to save, nor progress after this bug. The seed is: 8e3b5842 and the level takes place at the start of the forest of illusion if you want to encounter the bug yourself.
![bug](https://cloud.githubusercontent.com/assets/19922218/16031740/91a1605e-31b3-11e6-9b60-2b9a41f6d576.png)

**Comment by ZimPractical** [comment]
Also two side notes. 1: The glitch didn't happen in the same way after repeating the glitch multiple times, however every time the game still froze. 2: Even though the normal exit freezes, I was still able to get the secret exit just fine. Also some extra information about resolving the glitch, the level was a "no yoshi" level, but featured a yoshi in it, so maybe that can be a reason why the glitch happened. Or, it can just be the nature of the multiple paths and exits that may have thrown the program off.

**Comment by authorblues** [comment]
Should be fixed by https://github.com/authorblues/smwrandomizer/commit/49780d096598704d1645d104e33fa59d108c2e7c
