### ISSUE TITLE
Forest Ghost House

### ISSUE THREAD

**Issue by churine** [authorblues/smwrandomizer#9]
The second room is turned into the green bubble ghost house room
The blue door should lead to the black space at the first room, but instead puts mario inside the house like the yellow door.
seed 0146715f (_8d94), it's in the same world with only the sublevels changed

**Comment by authorblues** [comment]
Should be addressed by https://github.com/authorblues/smwrandomizer/commit/49780d096598704d1645d104e33fa59d108c2e7c
